name: Build M3U8 Downloader

on:
  push:
    branches: [ master ]  # ← Use your actual branch name
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt pyinstaller

      - name: Install FFmpeg
        run: |
          brew install ffmpeg

      - name: Build macOS app
        run: |
          python build.py

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt pyinstaller

      - name: Build Windows app
        run: |
          python build.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/
